<?php

namespace App\Filament\Resources\Assets\Pages;

use App\Filament\Resources\Assets\AssetResource;
use App\Filament\Widgets\AssetEvolutionChart;
use App\Models\Asset;
use App\Service\FiscalExportService;
use Filament\Actions\Action;
use Filament\Actions\EditAction;
use Filament\Resources\Pages\ViewRecord;
use Filament\Support\Icons\Heroicon;

class ViewAssets extends ViewRecord
{
    protected static string $resource = AssetResource::class;

    protected static ?string $title = "Fiche d'une Immobilisation";

    protected static ?string $breadcrumb = 'Fiche';

    protected function getHeaderActions(): array
    {
        return [
            EditAction::make()->label('Modifier'),
            Action::make('print')
                ->label('Imprimer')
                ->color('warning')
                ->icon(Heroicon::OutlinedPrinter)
                ->action(function (Asset $record, FiscalExportService $exportService) {
                    $pdfContent = $exportService->generateAssetReportPdf($record);

                    return response()->streamDownload(
                        fn () => print ($pdfContent),
                        "fiche_immo_{$record->reference}.pdf"
                    );
                }),
        ];
    }

    public function getFooterWidgetsColumns(): int|array
    {
        return 1;
    }

    protected function getFooterWidgets(): array
    {
        return [
            AssetEvolutionChart::class,
        ]; // TODO: Change the autogenerated stub
    }
}
