<?php

namespace App\Filament\Resources\Assets\Pages;

use App\Enums\AssetStatus;
use App\Filament\Resources\Assets\Actions\DisposeAction;
use App\Filament\Resources\Assets\Actions\RevaluateAction;
use App\Filament\Resources\Assets\AssetResource;
use App\Filament\Widgets\AssetEvolutionChart;
use App\Models\Asset;
use App\Service\FiscalExportService;
use Filament\Actions\Action;
use Filament\Actions\EditAction;
use Filament\Resources\Pages\ViewRecord;
use Filament\Support\Icons\Heroicon;
use Illuminate\Database\Eloquent\Model;

class ViewAssets extends ViewRecord
{
    protected static string $resource = AssetResource::class;

    protected static ?string $title = "Fiche d'une Immobilisation";

    protected static ?string $breadcrumb = 'Fiche';

    protected function getHeaderActions(): array
    {
        return [
            EditAction::make()->label('Modifier')->visible(fn (Model $record) => $record->status !== AssetStatus::Disposed),
            Action::make('print')
                ->label('Imprimer')
                ->color('warning')
                ->icon(Heroicon::OutlinedPrinter)
                ->action(function (Asset $record, FiscalExportService $exportService) {
                    $pdfContent = $exportService->generateAssetReportPdf($record);

                    return response()->streamDownload(
                        fn () => print ($pdfContent),
                        "fiche_immo_{$record->reference}.pdf"
                    );
                }),

            Action::make('print_disposal')
                ->visible(fn (Asset $record) => $record->status->value === AssetStatus::Disposed->value)
                ->label('Certificat de cession')
                ->color('success')
                ->icon(Heroicon::OutlinedPrinter)
                ->action(function (Asset $record, FiscalExportService $fiscalService) {
                    $pdfContent = $fiscalService->generateDisposalCertificatePdf($record);

                    return response()->streamDownload(
                        fn () => print ($pdfContent),
                        "certificat_sortie_{$record->reference}.pdf"
                    );
                }),
            RevaluateAction::make()->visible(fn (Model $record) => $record->status !== AssetStatus::Disposed),
            DisposeAction::make()
                ->label("Vendre l'objet")
                ->visible(fn (Asset $record) => $record->status !== AssetStatus::Disposed),
        ];
    }

    public function getFooterWidgetsColumns(): int|array
    {
        return 1;
    }

    protected function getFooterWidgets(): array
    {
        return [
            AssetEvolutionChart::class,
        ]; // TODO: Change the autogenerated stub
    }
}
